### ISSUE TITLE
undefined method crash on load

### ISSUE THREAD

**Issue by tsurezuregusa** [jreinert/autopass#17]
Hello,

Running autopass gives me a ruby error:

```
/usr/lib/ruby/2.3.0/ostruct.rb:170:in `new_ostruct_member': undefined method `to_sym' for #<Date: 2011-02-19 ((2455612j,0s,0n),+0s,2299161j)> (NoMethodError)
Did you mean?  to_s
    from /usr/lib/ruby/2.3.0/ostruct.rb:225:in `[]='
    from /home/desktop/.local/bin/autopass:47:in `block in expand_config'
    from /home/desktop/.local/bin/autopass:47:in `each'
    from /home/desktop/.local/bin/autopass:47:in `expand_config'
    from /home/desktop/.local/bin/autopass:326:in `entry_from'
    from /home/desktop/.local/bin/autopass:362:in `block in update_cache'
    from /home/desktop/.local/bin/autopass:360:in `each'
    from /home/desktop/.local/bin/autopass:360:in `update_cache'
    from /home/desktop/.local/bin/autopass:287:in `initialize'
    from /home/desktop/.local/bin/autopass:389:in `new'
    from /home/desktop/.local/bin/autopass:389:in `<main>'
```

It would seem I am missing some dependency, but I have all those listed here.
My system is on Debian testing.
Thanks.

**Comment by repomaa** [comment]
can you show me your config?

**Comment by repomaa** [comment]
Closing due to lack of information
